name: Run JS Tests (Jest)
on:
  push:
    branches: [dev, main, master]
  pull_request:
    branches: [dev, main, master]
defaults:
  run:
    working-directory: srcjs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run test
